### ISSUE TITLE
Error run "node cleanrooms.js"

### ISSUE THREAD

**Issue by ot-i-to** [groupboard/pingtest#1]
Hey,

The command "node cleanrooms.js" will throw an error "Unhandled rejection (<{"type":"error","isTrusted":false,"_ya...>, no stack trace)" ...  what's the problem?

System: Debian-11
Linux 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux

# nvm ls
    iojs-v3.3.1
->     v16.13.2
default -> iojs (-> iojs-v3.3.1)
unstable -> N/A (default)
node -> stable (-> v16.13.2) (default)
stable -> 16.13 (-> v16.13.2) (default)
iojs -> iojs-v3.3 (-> iojs-v3.3.1) (default)
lts/* -> lts/gallium (-> v16.13.2)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.10 (-> N/A)
lts/fermium -> v14.19.0 (-> N/A)
lts/gallium -> v16.13.2

# npm install janus-gateway-js
added 22 packages, and audited 23 packages in 7s
found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.4.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.1
npm notice Run npm install -g npm@8.4.1 to update!
npm notice

**Comment by groupboard** [comment]
What is the full error, and what line?

**Comment by ot-i-to** [comment]
just this

root@vm142:/var/www/html/pingtest# node cleanrooms.js
Unhandled rejection (<{"type":"error","isTrusted":false,"_ya...>, no stack trace)

**Comment by groupboard** [comment]
Try running with --trace-warnings: https://stackoverflow.com/a/47895841/1192732

**Comment by ot-i-to** [comment]
root@vm142:/var/www/html/pingtest# node --trace-warnings cleanrooms.js
Unhandled rejection (<{"type":"error","isTrusted":false,"_ya...>, no stack trace)

**Comment by groupboard** [comment]
Maybe "--trace-uncaught"?
If not, you might need to put in some debug to narrow it down to the line, then catch whatever exception or promise is being thrown.
