### ISSUE TITLE
Thanks for sharing this ping test application !

### ISSUE THREAD

**Issue by wastu01** [groupboard/pingtest#2]
I plan to use chart js chart to dynamically present ping values based on this project, and I am thinking about how to make it.

https://github.com/wastu01/Chartjs-demo

**Comment by wastu01** [comment]
I have a problem that it show me "Janus is not defined" when I put server to my janus

`var opaqueId = "pingtest-"+Janus.randomString(12);`

```
//var server = null;
var server = "/janus";
if(window.location.protocol === 'http:')
        server = "http://" + window.location.hostname + ":8088/janus";
else
        server = "https://" + window.location.hostname + ":8089/janus";

server="http://xx.xx.xx.xx:8088/janus";

console.log(server);

```

**Comment by groupboard** [comment]
Sounds like you're missing janus.js, which is where Janus is defined.

**Comment by wastu01** [comment]
tks for helping !

**Comment by wastu01** [comment]
I solve the problem. Thanks
It need to set up janus server 
`docker exec -it janus bash "/opt/janus/bin/janus -S stun.l.google.com:19305 &"`

**Comment by wastu01** [comment]
As Javascript beginner, I want to ask more detail about pingtest.js
I do not see any id = datasend in html
```
                oncleanup: function() {
                        Janus.log(" ::: Got a cleanup notification :::");
                        $('#datasend').attr('disabled', true);
                }
```

**Comment by groupboard** [comment]
The datasend isn't needed. It's from the text chat demo. Now removed.

**Comment by wastu01** [comment]
Got it ! Tks for replying
